CREATE TABLE `item_rondas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`itemId` int NOT NULL,
	`numeroRonda` int NOT NULL DEFAULT 1,
	`fotoAntesUrl` text,
	`fotoAntesKey` varchar(255),
	`fotoAntesBase64` text,
	`fotoAntesMarcadaUrl` text,
	`fotoAntesMarcadaKey` varchar(255),
	`fotoAntesMarcadaBase64` text,
	`fotoDespuesUrl` text,
	`fotoDespuesKey` varchar(255),
	`fotoDespuesBase64` text,
	`status` enum('pendiente_foto_despues','pendiente_aprobacion','aprobado','rechazado') NOT NULL DEFAULT 'pendiente_foto_despues',
	`creadoPorId` int,
	`revisadoPorId` int,
	`comentarioRevision` text,
	`fechaCreacion` timestamp NOT NULL DEFAULT (now()),
	`fechaFotoDespues` timestamp,
	`fechaRevision` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `item_rondas_id` PRIMARY KEY(`id`)
);
